# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: niriblue
description: Custom niri image built on wayblue

base-image: ghcr.io/wayblueorg/niri
image-version: latest

modules:
  - type: dnf
    repos:
      copr:
        - atim/starship
        - scottames/ghostty
        - dejan/lazygit
        - peterwu/rendezvous
    install:
      packages:
        - alacritty
        - bibata-cursor-themes
        - cosmic-files
        - cosmic-settings
        - fd-find
        - ghostty
        - grim
        - jetbrains-mono-fonts-all
        - lazygit
        - neovim
        - noctalia
        - pamixer
        - podman-compose
        - slurp
        - starship
        - tealdeer
        - gamemode
        - mangohud
        - gamescope

  - type: default-flatpaks
    configurations:
      - scope: system
        install:
          - com.valvesoftware.Steam

  - type: signing
