# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: niriblue
description: Custom niri image built on Fedora Atomic base

base-image: quay.io/fedora-ostree-desktops/base-atomic
image-version: 44

modules:
  - type: files
    files:
      - source: system
        destination: /

  - type: dnf
    repos:
      copr:
        - atim/starship
        - scottames/ghostty
        - dejan/lazygit
        - peterwu/rendezvous
        - ublue-os/packages
      files:
        - https://negativo17.org/repos/fedora-multimedia.repo
    install:
      packages:
        - alacritty
        - bibata-cursor-themes
        - cosmic-files
        - cosmic-settings
        - fd-find
        - ghostty
        - grim
        - jetbrains-mono-fonts-all
        - lazygit
        - neovim
        - noctalia
        - pamixer
        - podman-compose
        - slurp
        - starship
        - tealdeer
        - niri
        - xwayland-satellite
        - mate-polkit
        - xdg-desktop-portal-gtk
        - xdg-desktop-portal-gnome
        - sddm
        - sddm-themes
        - qt5-qtgraphicaleffects
        - qt5-qtquickcontrols2
        - qt5-qtsvg
        - kwallet
        - pam-kwallet
        - pipewire
        - wireplumber
        - pipewire-pulseaudio
        - bluez
        - default-fonts-core-sans
        - google-noto-emoji-fonts
        - ffmpeg
        - libva-utils
        - gamemode
        - mangohud
        - gamescope
        - ublue-os-udev-rules
        - uupd
        - gnome-keyring-pam
        - code

  - type: dnf
    remove:
      packages:
        - waybar

  - type: containerfile
    snippets:
      - COPY --from=ghcr.io/ublue-os/akmods:ogc-44 /rpms /tmp/rpms
      - COPY --from=ghcr.io/ublue-os/akmods:ogc-44 /kernel-rpms /tmp/rpms/kernel
      - RUN dnf install -y /tmp/rpms/ublue-os/ublue-os-akmods-addons*.rpm

  - type: script
    scripts:
      - install-ogc-kernel.sh

  - type: akmods
    base: ogc
    install:
      - xone

  - type: script
    scripts:
      - noctalia-default.sh
      - sddm-theming.sh
      - regenerate-initramfs.sh

  - type: default-flatpaks
    configurations:
      - scope: system
        install:
          - com.valvesoftware.Steam

  - type: systemd
    system:
      enabled:
        - sddm.service
        - sddm-boot.service
        - uupd.timer
    user:
      enabled:
        - podman.socket

  - type: signing
